---
- hosts: localhost
  user: ryan
  connection: local

  vars_prompt:
    - name: "mas_email"
      prompt: "Enter email for Mac App Store"
      private: no
    - name: "mas_password"
      prompt: "Enter password for Mac App Store"
      private: yes

  vars:
    dotfiles_repo: https://github.com/ryanb93/dotfiles.git
    dotfiles_repo_accept_hostkey: yes
    dotfiles_repo_local_destination: ~/.dotfiles
    dotfiles_files:
      - .functions
      - .exports
      - .aliases
    mas_installed_app_ids:
      - 972028355 # Micro Snitch
      - 552383089 # Dashlane
      - 409201541 # Pages
      - 497799835 # Xcode
      - 463243494 # Kopypasta
      - 585829637 # Todoist
      - 409203825 # Numbers

  roles:
    - system
    - ryan
    - geerlingguy.dotfiles
    - name: geerlingguy.mas
      when: mas_installed_app_ids

