---
- hosts: localhost
  user: ryan
  connection: local

  vars_prompt:
    - name: "mas_email"
      prompt: "Enter email for Mac App Store"
      private: no

  vars:
  - vars:
    dotfiles_repo: https://github.com/ryanb93/dotfiles.git
    dotfiles_repo_accept_hostkey: yes
    dotfiles_repo_local_destination: ~/.dotfiles
    dotfiles_files:
      - .aliases
      - .agignore
      - .exports
      - .functions
      - .gemrc
      - .gitconfig
      - .gitignore
      - .irbrc
      - .rspec
      - .tmux.conf
      - .zprofile

  roles:
    - system
    - geerlingguy.dotfiles
    - ryan