---
- name: Defaults | Update Homebrew
  homebrew: update_homebrew=yes

- name: Defaults | Update Homebrew taps
  homebrew_tap: name={{ item }} state=present
  with_items:
    - caskroom/fonts
    - gapple/services
    - homebrew/dupes
    - homebrew/science
    - homebrew/versions

- name: Defaults | Update Homebrew & Taps
  homebrew: update_homebrew=yes upgrade_all=yes

- name: Defaults | Install Homebrew casks
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - caffeine
    - little-snitch
    - iterm2
    - java
    - unrarx
    - virtualbox

- name: Defaults | Install Homebrew packages
  homebrew: name={{ item }} state=upgraded
  with_items:
    - ansible
    - autojump
    - automake
    - cloc
    - coreutils
    - curl
    - findutils
    - git
    - git-extras
    - gpg
    - htop-osx
    - imagemagick
    - mas
    - maven
    - nmap
    - openssl
    - reattach-to-user-namespace
    - sbt
    - scala
    - sox
    - the_silver_searcher
    - thefuck
    - tig
    - tmux
    - vim
    - wget
    - zsh
    - zsh-completions
    - zsh-syntax-highlighting
