---
- name: Apps | Install Homebrew casks
  homebrew_cask: name={{ item }} state=installed
  ignore_errors: true
  with_items:
    - airflow
    - appcleaner
    - audacity
    - betterzipql
    - caffeine
    - coconutbattery
    - docker
    - firefox
    - flux
    - hexfiend'
    - hipchat
    - insomniax
    - intellijidea'
    - iterm2
    - java
    - littlesnitch'
    - mou
    - nordvpn
    - qlcolorcode
    - qlmarkdown
    - qlprettypatch
    - qlstephen
    - quicklookcsv'
    - quicklookjson'
    - runescape
    - sourcetree
    - spotify
    - steam
    - sublimetext'
    - suspiciouspackage'
    - transmission
    - unrarx
    - virtualbox
    - vlc
    - webpquicklook