- name: Mac App Store | Check if logged in
  command: mas account
  ignore_errors: True
  register: account_is_logged_in

- name: Mac App Store | Log out current user
  command: mas signout
  when: account_is_logged_in|succeeded
